### ISSUE TITLE
Invalid cs script name "responder.cs" in UnityResponder/demo

### ISSUE THREAD

**Issue by jinPrelude** [ysf199711/Python-Unity-ZMQ#1]
Script name "responder.cs" in UnityResponder/demo should be changed as "Responder.cs". It cause error : `the script don't inherit a native class that can manage a script`.
The name of the script must match with class name.

**Comment by sye8** [comment]
Filename updated, can you verify that the error has gone?

**Comment by jinPrelude** [comment]
Thanks! One thing that should be fixed is that unity ignore both "resonder.cs" and "Responder.cs" since it has the same name. Deleting "responder.cs" would make it work. Your repo is amazing it really helped a lot.

**Comment by sye8** [comment]
Thanks for the heads up. Lower case files removed
